using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Loads the modular environment pieces generated by
/// Tools/Blender/build_environment_kit.py from Assets/Resources/Art/Kit.
/// Every lookup returns null when a piece is missing, so the primitive
/// builders in WorldStyler keep working unchanged until the kit FBX files
/// are generated and imported.
///
/// Kit pieces are vertex-colored meshes: RGB is the base color and the alpha
/// channel marks the emissive glow mask, the same convention as the
/// EchoRunner character. Spawn applies the shared EchoRun/VertexColor shader
/// so no per-piece material assets are required.
/// </summary>
public static class EchoEnvironmentKit
{
    public const string KitResourceFolder = "Art/Kit";
    public const string VertexColorShaderName = "EchoRun/VertexColor";

    private static readonly Dictionary<string, GameObject> _cache =
        new Dictionary<string, GameObject>();
    private static readonly HashSet<string> _missing =
        new HashSet<string>();
    private static Material _sharedMaterial;

    public static bool Has(string pieceName)
    {
        return LoadPrefab(pieceName) != null;
    }

    public static GameObject Spawn(string pieceName, Transform parent,
        Vector3 localPosition, Vector3 localEulerAngles, Vector3 localScale)
    {
        GameObject prefab = LoadPrefab(pieceName);
        if (prefab == null || parent == null) return null;

        GameObject instance = Object.Instantiate(prefab, parent, false);
        instance.name = pieceName;
        instance.transform.localPosition = localPosition;
        instance.transform.localEulerAngles = localEulerAngles;
        instance.transform.localScale = localScale;
        ApplySharedMaterial(instance);
        return instance;
    }

    public static GameObject Spawn(string pieceName, Transform parent,
        Vector3 localPosition)
    {
        return Spawn(pieceName, parent, localPosition, Vector3.zero,
            Vector3.one);
    }

    private static GameObject LoadPrefab(string pieceName)
    {
        if (string.IsNullOrEmpty(pieceName)) return null;
        if (_cache.TryGetValue(pieceName, out GameObject cached))
            return cached;
        if (_missing.Contains(pieceName)) return null;

        GameObject prefab = Resources.Load<GameObject>(
            KitResourceFolder + "/" + pieceName);
        if (prefab == null)
        {
            _missing.Add(pieceName);
            return null;
        }
        _cache[pieceName] = prefab;
        return prefab;
    }

    private static void ApplySharedMaterial(GameObject instance)
    {
        if (_sharedMaterial == null)
        {
            Shader shader = Shader.Find(VertexColorShaderName);
            if (shader == null) return;
            _sharedMaterial = new Material(shader)
            {
                name = "EchoKit_VertexColor"
            };
        }

        Renderer[] renderers =
            instance.GetComponentsInChildren<Renderer>(true);
        for (int i = 0; i < renderers.Length; i++)
            renderers[i].sharedMaterial = _sharedMaterial;
    }
}
