using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Loads the geometric line icons generated by Tools/Icons/generate_icons.py
/// from Assets/Resources/Art/Icons. Textures import as default (non-sprite)
/// assets, so sprites are created at runtime; every lookup returns null when
/// an icon is missing, letting callers hide the glyph and keep the text.
/// </summary>
public static class EchoIconSet
{
    public const string IconResourceFolder = "Art/Icons";

    private static readonly Dictionary<string, Sprite> _cache =
        new Dictionary<string, Sprite>();
    private static readonly HashSet<string> _missing =
        new HashSet<string>();

    public static bool Has(string iconName)
    {
        return Get(iconName) != null;
    }

    public static Sprite Get(string iconName)
    {
        if (string.IsNullOrEmpty(iconName)) return null;
        if (_cache.TryGetValue(iconName, out Sprite cached))
            return cached;
        if (_missing.Contains(iconName)) return null;

        Texture2D texture = Resources.Load<Texture2D>(
            IconResourceFolder + "/" + iconName);
        if (texture == null)
        {
            _missing.Add(iconName);
            return null;
        }

        Sprite sprite = Sprite.Create(
            texture,
            new Rect(0f, 0f, texture.width, texture.height),
            new Vector2(0.5f, 0.5f), 100f);
        sprite.name = iconName;
        _cache[iconName] = sprite;
        return sprite;
    }
}
