name: Acquire Unity activation file

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:
  activation:
    name: Request Unity manual activation file
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Request manual activation file
        id: activation
        uses: game-ci/unity-request-activation-file@65874ef791dae6dfa5829f1cb490eafbd7b2173c # v2

      - name: Upload activation file
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ steps.activation.outputs.filePath }}
          path: ${{ steps.activation.outputs.filePath }}
          if-no-files-found: error
          retention-days: 1
